#!/bin/bash

cat  ${0##*/} 
read -p "Press any key to continue... " -n1 -s
mydir=`pwd`
cd java
javac ru/ifmo/rain/Petrovski/helloudp/HelloUDPClient.java
cd info/kgeorgiy/java/advanced/hello/
rm *.class
cd $mydir/java
java -cp ./:../artifacts/HelloUDPTest.jar:../lib/hamcrest-core-1.3.jar:../lib/jsoup-1.8.1.jar:../lib/junit-4.11.jar:../lib/quickcheck-0.6.jar info.kgeorgiy.java.advanced.hello.Tester client-i18n ru.ifmo.rain.Petrovski.helloudp.HelloUDPClient "$1"
cd ..

